In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [24]:
df=pd.read_csv("spotify_songs.csv", index_col=1)
df

,track_id,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,playlist_subgenre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
track_name,,,,,,,,,,,,,,,,,,,,,
I Don't Care (with Justin Bieber) - Loud Luxury Remix,6f807x0ima9a1j3VPbc7VN,Ed Sheeran,66,2oCs0DGTsRO98Gh5ZSl2Cx,I Don't Care (with Justin Bieber) [Loud Luxury...,2019-06-14,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,dance pop,...,6,-2.634,1,0.0583,0.102000,0.000000,0.0653,0.5180,122.036,194754
Memories - Dillon Francis Remix,0r7CVbZTWZgbTCYdfa2P31,Maroon 5,67,63rPSO264uRjW1X5E6cWv6,Memories (Dillon Francis Remix),2019-12-13,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,dance pop,...,11,-4.969,1,0.0373,0.072400,0.004210,0.3570,0.6930,99.972,162600
All the Time - Don Diablo Remix,1z1Hg7Vb0AhHDiEmnDE79l,Zara Larsson,70,1HoSmj2eLcsrR0vE9gThr4,All the Time (Don Diablo Remix),2019-07-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,dance pop,...,1,-3.432,0,0.0742,0.079400,0.000023,0.1100,0.6130,124.008,176616
Call You Mine - Keanu Silva Remix,75FpbthrwQmzHlBJLuGdC7,The Chainsmokers,60,1nqYsOef1yKKuGOVchbsk6,Call You Mine - The Remixes,2019-07-19,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,dance pop,...,7,-3.778,1,0.1020,0.028700,0.000009,0.2040,0.2770,121.956,169093
Someone You Loved - Future Humans Remix,1e8PAfcKUYoKkxPhrHqw4x,Lewis Capaldi,69,7m7vv9wlQ4i0LFuJiE2zsQ,Someone You Loved (Future Humans Remix),2019-03-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,dance pop,...,1,-4.672,1,0.0359,0.080300,0.000000,0.0833,0.7250,123.976,189052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
City Of Lights - Official Radio Edit,7bxnKAamR3snQ1VGLuVfC1,Lush & Simon,42,2azRoBBWEEEYhqV6sb7JrT,City Of Lights (Vocal Mix),2014-04-28,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,progressive electro house,...,2,-1.814,1,0.0936,0.076600,0.000000,0.0668,0.2100,128.170,204375
Closer - Sultan & Ned Shepard Remix,5Aevni09Em4575077nkWHz,Tegan and Sara,20,6kD6KLxj7s8eCE3ABvAyf5,Closer Remixed,2013-03-08,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,progressive electro house,...,0,-4.462,1,0.0420,0.001710,0.004270,0.3750,0.4000,128.041,353120
Sweet Surrender - Radio Edit,7ImMqPP3Q1yfUHvsdn7wEo,Starkillers,14,0ltWNSY9JgxoIZO4VzuCa6,Sweet Surrender (Radio Edit),2014-04-21,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,progressive electro house,...,6,-4.899,0,0.0481,0.108000,0.000001,0.1500,0.4360,127.989,210112
Only For You - Maor Levi Remix,2m69mhnfQ1Oq6lGtXuYhgX,Mat Zo,15,1fGrOkHnHJcStl14zNx8Jy,Only For You (Remixes),2014-01-01,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,progressive electro house,...,2,-3.361,1,0.1090,0.007920,0.127000,0.3430,0.3080,128.008,367432
Typhoon - Original Mix,29zWqhca3zt5NsckZqDf6c,Julian Calor,27,0X3mUOm6MhxR7PzxG95rAo,Typhoon/Storm,2014-03-03,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,progressive electro house,...,5,-4.571,0,0.0385,0.000133,0.341000,0.7420,0.0894,127.984,337500

In [25]:
df.drop(["track_id", "track_album_id", "playlist_id", "playlist_name", "playlist_genre", "playlist_subgenre"], inplace=True, axis=1)

In [26]:
df.drop_duplicates(inplace=True)
df.dropna(inplace=True)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28345 entries, I Don't Care (with Justin Bieber) - Loud Luxury Remix to Typhoon - Original Mix
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   track_artist              28345 non-null  object
 1   track_popularity          28345 non-null  int64
 2   track_album_name          28345 non-null  object
 3   track_album_release_date  28345 non-null  object
 4   danceability              28345 non-null  float64
 5   energy                    28345 non-null  float64
 6   key                       28345 non-null  int64
 7   loudness                  28345 non-null  float64
 8   mode                      28345 non-null  int64
 9   speechiness               28345 non-null  float64
 10  acousticness              28345 non-null  float64
 11  instrumentalness          28345 non-null  float64
 12  liveness                  28345 non-null  float64
 13  valence                   28345 non-null  float64
 14  tempo                     28345 non-null  float64
 15  duration_ms               28345 non-null  int64
dtypes: float64(9), int64(4), object(3)
memory usage: 3.7+ MB

In [28]:
df

,track_artist,track_popularity,track_album_name,track_album_release_date,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
track_name,,,,,,,,,,,,,,,,
I Don't Care (with Justin Bieber) - Loud Luxury Remix,Ed Sheeran,66,I Don't Care (with Justin Bieber) [Loud Luxury...,2019-06-14,0.748,0.916,6,-2.634,1,0.0583,0.102000,0.000000,0.0653,0.5180,122.036,194754
Memories - Dillon Francis Remix,Maroon 5,67,Memories (Dillon Francis Remix),2019-12-13,0.726,0.815,11,-4.969,1,0.0373,0.072400,0.004210,0.3570,0.6930,99.972,162600
All the Time - Don Diablo Remix,Zara Larsson,70,All the Time (Don Diablo Remix),2019-07-05,0.675,0.931,1,-3.432,0,0.0742,0.079400,0.000023,0.1100,0.6130,124.008,176616
Call You Mine - Keanu Silva Remix,The Chainsmokers,60,Call You Mine - The Remixes,2019-07-19,0.718,0.930,7,-3.778,1,0.1020,0.028700,0.000009,0.2040,0.2770,121.956,169093
Someone You Loved - Future Humans Remix,Lewis Capaldi,69,Someone You Loved (Future Humans Remix),2019-03-05,0.650,0.833,1,-4.672,1,0.0359,0.080300,0.000000,0.0833,0.7250,123.976,189052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
City Of Lights - Official Radio Edit,Lush & Simon,42,City Of Lights (Vocal Mix),2014-04-28,0.428,0.922,2,-1.814,1,0.0936,0.076600,0.000000,0.0668,0.2100,128.170,204375
Closer - Sultan & Ned Shepard Remix,Tegan and Sara,20,Closer Remixed,2013-03-08,0.522,0.786,0,-4.462,1,0.0420,0.001710,0.004270,0.3750,0.4000,128.041,353120
Sweet Surrender - Radio Edit,Starkillers,14,Sweet Surrender (Radio Edit),2014-04-21,0.529,0.821,6,-4.899,0,0.0481,0.108000,0.000001,0.1500,0.4360,127.989,210112
Only For You - Maor Levi Remix,Mat Zo,15,Only For You (Remixes),2014-01-01,0.626,0.888,2,-3.361,1,0.1090,0.007920,0.127000,0.3430,0.3080,128.008,367432
Typhoon - Original Mix,Julian Calor,27,Typhoon/Storm,2014-03-03,0.603,0.884,5,-4.571,0,0.0385,0.000133,0.341000,0.7420,0.0894,127.984,337500

In [29]:
albuns=df[df["track_album_release_date"]=="2012"]["track_album_name"].value_counts().index
albuns=list(albuns)

In [32]:
# Normalize year-only release dates like '2012' to '2012-01-01'
df['track_album_release_date'] = df['track_album_release_date'].astype(str).str.strip()
mask = df['track_album_release_date'].str.match(r'^\d{4}$')
df.loc[mask, 'track_album_release_date'] = df.loc[mask, 'track_album_release_date'] + '-01-01'
# Now parse all dates using YYYY-MM-DD format
pd.to_datetime(df['track_album_release_date'], format='mixed')

track_name
I Don't Care (with Justin Bieber) - Loud Luxury Remix   2019-06-14
Memories - Dillon Francis Remix                         2019-12-13
All the Time - Don Diablo Remix                         2019-07-05
Call You Mine - Keanu Silva Remix                       2019-07-19
Someone You Loved - Future Humans Remix                 2019-03-05
                                                           ...
City Of Lights - Official Radio Edit                    2014-04-28
Closer - Sultan & Ned Shepard Remix                     2013-03-08
Sweet Surrender - Radio Edit                            2014-04-21
Only For You - Maor Levi Remix                          2014-01-01
Typhoon - Original Mix                                  2014-03-03
Name: track_album_release_date, Length: 28345, dtype: datetime64[ns]

In [33]:
df

,track_artist,track_popularity,track_album_name,track_album_release_date,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
track_name,,,,,,,,,,,,,,,,
I Don't Care (with Justin Bieber) - Loud Luxury Remix,Ed Sheeran,66,I Don't Care (with Justin Bieber) [Loud Luxury...,2019-06-14,0.748,0.916,6,-2.634,1,0.0583,0.102000,0.000000,0.0653,0.5180,122.036,194754
Memories - Dillon Francis Remix,Maroon 5,67,Memories (Dillon Francis Remix),2019-12-13,0.726,0.815,11,-4.969,1,0.0373,0.072400,0.004210,0.3570,0.6930,99.972,162600
All the Time - Don Diablo Remix,Zara Larsson,70,All the Time (Don Diablo Remix),2019-07-05,0.675,0.931,1,-3.432,0,0.0742,0.079400,0.000023,0.1100,0.6130,124.008,176616
Call You Mine - Keanu Silva Remix,The Chainsmokers,60,Call You Mine - The Remixes,2019-07-19,0.718,0.930,7,-3.778,1,0.1020,0.028700,0.000009,0.2040,0.2770,121.956,169093
Someone You Loved - Future Humans Remix,Lewis Capaldi,69,Someone You Loved (Future Humans Remix),2019-03-05,0.650,0.833,1,-4.672,1,0.0359,0.080300,0.000000,0.0833,0.7250,123.976,189052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
City Of Lights - Official Radio Edit,Lush & Simon,42,City Of Lights (Vocal Mix),2014-04-28,0.428,0.922,2,-1.814,1,0.0936,0.076600,0.000000,0.0668,0.2100,128.170,204375
Closer - Sultan & Ned Shepard Remix,Tegan and Sara,20,Closer Remixed,2013-03-08,0.522,0.786,0,-4.462,1,0.0420,0.001710,0.004270,0.3750,0.4000,128.041,353120
Sweet Surrender - Radio Edit,Starkillers,14,Sweet Surrender (Radio Edit),2014-04-21,0.529,0.821,6,-4.899,0,0.0481,0.108000,0.000001,0.1500,0.4360,127.989,210112
Only For You - Maor Levi Remix,Mat Zo,15,Only For You (Remixes),2014-01-01,0.626,0.888,2,-3.361,1,0.1090,0.007920,0.127000,0.3430,0.3080,128.008,367432
Typhoon - Original Mix,Julian Calor,27,Typhoon/Storm,2014-03-03,0.603,0.884,5,-4.571,0,0.0385,0.000133,0.341000,0.7420,0.0894,127.984,337500